alias: "Piscine — Arrêter pompe quand surplus insuffisant"
description: "Arrête la pompe si production < 700W ou import > 200W pendant 1 min."
trigger:
  - platform: numeric_state
    entity_id: sensor.current_power_production
    below: 700
    for: "00:01:00"
  - platform: numeric_state
    entity_id: sensor.msunpv_powreso
    above: 200
    for: "00:01:00"
condition:
  - condition: state
    entity_id: switch.piscine_relais
    state: "on"
  - condition: template
    value_template: >
      {{ now() > as_datetime(state_attr('sun.sun', 'next_rising')) + timedelta(hours=3) }}
action:
  - service: switch.turn_off
    target:
      entity_id: switch.piscine_relais
mode: single
